### PR TITLE
add ajax call on crete question div

### PR DESCRIPTION
**Pull request by alexjtark**
ajax call currently commented out, as it need styling, but it works.

### CODE REVIEW

**Comment by alexjtark** [comment]
@HeyCampbell @dlrifkin @sagararathi @dxr4841  for review from one of you.

**Comment by HeyCampbell** [comment]
Just merged it, but the form seems to break in the ajax call and I can’t add questions. Is it something to do with the listener not being on the page when it is loaded?

---

Jon Campbell
M: 646.662.6806 
heycampbell@gmail.com

**Comment by HeyCampbell** [comment]
It's my suspicion. That is why it is commented out for possible future
implementation once I can get the bug fixed.

**Comment by HeyCampbell** [comment]
Cool, I just messed with it a bit. I moved the whole question and answer button functions into the .done on your ajax call. So they bind when that is loaded. I don’t know if we need to keep the original route anymore, what you implemented is awesome and adds a ton of functionality.

---

Jon Campbell
M: 646.662.6806 
heycampbell@gmail.com

**Pull request merged**
